services:
  spring-app:
    image: myapp:latest
    container_name: spring-app
    ports:
      - "8080:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - spring-app
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
