version: '2'

services:
  app:
    image: myapp
    ports:
      - "443:443"
    build: .
    volumes:
      - .:/usr/src/myapp
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: mvn spring-boot:run
#    depends_on:
#      - db
#    environment:
#      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5443/giga_requirements
#      - SPRING_LIQUIBASE_URL=jdbc:postgresql://db:5443/giga_requirements
#      - SPRING_DATASOURCE_USERNAME=postgres
#      - SPRING_DATASOURCE_PASSWORD=2236

#  db:
#    image: 'postgres:latest'
#    container_name: db
#    environment:
#      - POSTGRES_USER=postgres
#      - POSTGRES_PASSWORD=2236
#      - POSTGRES_DB=restaurant
#      - PG_PORT=5443