version: '3.8'

services:
  spring-app:
    image: myapp:latest
    container_name: spring-app
    ports:
      - "8090:8090"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
      - SERVER_PORT=8090
    networks:
      - app-network
  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
      - /etc/letsencrypt:/etc/letsencrypt
    depends_on:
      - spring-app
    networks:
      - app-network

networks:
  app-network:
    driver: bridge