services:
  app:
    image: myapp
    build: .
    volumes:
      - .:/usr/src/myapp
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    command: mvn spring-boot:run
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.app.rule=Host(`backend.$DOMAIN`)"
      - "traefik.http.services.app.loadbalancer.server.port=8090"
      - "traefik.http.routers.app.entrypoints=websecure"
      - "traefik.http.routers.app.tls.certresolver=myresolver"

  traefik:
    image: traefik:latest
    container_name: traefik
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/etc/traefik/traefik.yml
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"