server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: mappings

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/myappdb
    username: manager
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect